### ISSUE TITLE
The workflow doesn't seem to work

### ISSUE THREAD

**Issue by slnc** [gshewakr/alfred-whatsapp-toolkit#1]
After installing the workflow on Mac OSX 12.4 with WhatsApp App 2.2216.8, when I type "wa", Alfred shows me the workflow icon, but then when I type enter and type part of the name of a contact or the full exact name, nothing happens, WhatsApp App doesn't come to the foreground and if I have the WhatsApp app open, I don't see anything happening there either.

**Comment by gshewakr** [comment]
I've not set it up to pull from your list of contacts (because presumably those individuals are already in your WhatsApp contact list). This is for numbers that aren't in your contact list, so you'd need to put in `wa <phone number>`

**Comment by slnc** [comment]
Thanks for the clarification. 

Consider changing the README.md description ("This is a simple Alfred workflow that makes it easy to initiate WhatsApp messages from Alfred.") I interpreted as "you can type "wa some_name message" and send a message easily. It would have never ocurred to me that instead it does what you described.
